sudo: required

services:
  - docker

env:
  - TRAVIS_CI_BUILD=true

script:
  # Build .apk file and build docker image (inside docker container)
  - docker run --rm -v $(pwd)/:/build -w /build -e TRAVIS_CI_BUILD clemenshuebner/amos-ss16-proj8-ionic-build:1.0 docker/build

  # Build docker image based on amos-downloader-image and push it  
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull hannesd/amos-downloader-image:1.0
  - docker build -t clemenshuebner/amos-ss16-proj8:1.0 docker/
  - docker push clemenshuebner/amos-ss16-proj8:1.0