
sudo: required

services:
  - docker

env:
  - TRAVIS_CI_BUILD=true

script:
  # Build .apk file and build docker image (inside docker container)
  - docker run --rm -v $(pwd)/:/build -w /build -e TRAVIS_CI_BUILD osrgroup/amos-android-build-image:1.0 docker/build

  # Build docker image
  # --pull: Make sure that the newest version of the base image is always pulled
  - docker build --pull -t osrgroup/android-app-example-project:1.0 docker/

<<<<<<< HEAD
  # Log in to Docker Hub and push the image we've just build
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push osrgroup/android-app-example-project:1.0
=======
after_script:
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
 - docker pull hannesd/amos-downloader-image:1.0
 - docker build -t clemenshuebner/amos-ss16-proj8:1.0 docker/
 - docker push clemenshuebner/amos-ss16-proj8:1.0
 - echo "Finished deployment to Docker"
>>>>>>> 111a3b17f7828865087ddcc5501cf94d5efeafa7
