language: android
android:
  components:
    - build-tools-23.1
    - android-23

before_script:
  - npm install -g cordova ionic
  - npm install -g gulp
  - cd proof-of-concept/conference-app/
  - chmod +x hooks/after_prepare/010_add_platform_class.js
  - cordova platform add android --save
  - npm install --save
script: docker/build